### ISSUE TITLE
SPM - Projects missing executable binaries in repository

### ISSUE THREAD

**Issue by ThePragmaticArt** [Scandit/datacapture-spm-core#1]
As of now, the repositories for SPM only contain the Package file and a blank README:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/4037188/113929655-4f99ec00-97be-11eb-9fab-cfc63161434c.png">

The executable binary specified below is not part of the current repositories (this applies to all of Scandit's SPM libraries)

```
let package = Package(
    name: "ScanditCaptureCore",
    platforms: [.iOS(.v10)],
    products: [
        .library(
            name: "ScanditCaptureCore",
            targets: ["ScanditCaptureCore"]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(name: "ScanditCaptureCore", url: "https://ssl.scandit.com/sdk/download/scandit-datacapture-ios-core-6.7.1-xcframework.zip", checksum: "e5f3281a587044830c5918caa5e551a1365d9045343a88104aebc03f5b6bd0d4")
    ]
)
```

Note the following [inclusion docs](https://docs.scandit.com/data-capture-sdk/ios/add-sdk.html) from the Scandit 6.xx documentation which will not work because of this:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/4037188/113929804-76582280-97be-11eb-8e0a-8ee68f2f1bee.png">

**Comment by lucatorella** [comment]
Hi @ThePragmaticArt, I'm not sure I understand your comment. You say 

> The executable binary specified below is not part of the current repositories

but I don't see why this would be an issue. SPM doesn't restrict where the binaries are.
